name: Release
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    name: Release build and publish
    runs-on: macos-latest

    permissions:
      contents: write # Needed for release assets if applicable, good practice for publishing
      packages: write # Crucial for publishing to GitHub Packages

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Create local.properties
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Build
        run: ./gradlew assemble --stacktrace -PmavenUsername=${{ secrets.CURRENT_GITHUB_USER }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}

      - name: Release library
        run: ./gradlew halo:publish -PmavenUsername=${{ secrets.CURRENT_GITHUB_USER }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}
