name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Tagged build and publish
    runs-on: macos-latest

    permissions:
      contents: write # Needed for release assets if applicable, good practice for publishing
      packages: write # Crucial for publishing to GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Create local.properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Extract Git Tag
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build with Tag Version
        run: ./gradlew assemble --stacktrace -Pversion=$TAG_NAME -PmavenUsername=${{ secrets.CURRENT_GITHUB_USER }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}

      - name: Publish Halo Library
        run: ./gradlew halo:publish -Pversion=$TAG_NAME -PmavenUsername=${{ secrets.CURRENT_GITHUB_USER }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}

      - name: Publish Charts Library
        run: ./gradlew charts:publish -Pversion=$TAG_NAME -PmavenUsername=${{ secrets.CURRENT_GITHUB_USER }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}
